
version: '3.8'  
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cafe_management
      MYSQL_USER: shoaib
      MYSQL_PASSWORD: shoaib
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: shoaib
      DB_PASSWORD: shoaib
      DB_NAME: cafe_management